config/routes.rb
Rails.application.routes.draw do
  resources :tareas
  resources :categorias
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/Categoria.rb
# == Schema Information
#
# Table name: categoria
#
#  id          :bigint           not null, primary key
#  nombre      :string
#  descripcion :text
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#
class Categoria < ApplicationRecord
  has_many:tarea # indicamos el modelo con el que hacemos la relación
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/tarea.rb
# == Schema Information
#
# Table name: tareas
#
#  id                :bigint           not null, primary key
#  nombre            :string
#  descripcion       :text
#  fecha_vencimiento :date
#  categoria_id      :bigint           not null
#  created_at        :datetime         not null
#  updated_at        :datetime         not null
#
class Tarea < ApplicationRecord
  belongs_to :categoria
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/categoria_controller.rb
class CategoriaController < ApplicationController
  before_action :set_categorium, only: %i[ show edit update destroy ]

  # GET /categoria or /categoria.json
  def index
    @categoria = Categoria.all
  end

  # GET /categoria/1 or /categoria/1.json
  def show
  end

  # GET /categoria/new
  def new
    @categoria = Categoria.new
  end

  # GET /categoria/1/edit
  def edit
  end

  # POST /categoria or /categoria.json
  def create
    @categoria = Categoria.new(categoria_params)

    respond_to do |format|
      if @categoria.save
        format.html { redirect_to @categoria, notice: "Categorium was successfully created." }
        format.json { render :show, status: :created, location: @categoria }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @categoria.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /categoria/1 or /categoria/1.json
  def update
    respond_to do |format|
      if @categoria.update(categoria_params)
        format.html { redirect_to @categoria, notice: "Categorium was successfully updated." }
        format.json { render :show, status: :ok, location: @categoria }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @categoria.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categoria/1 or /categoria/1.json
  def destroy
    @categoria.destroy!

    respond_to do |format|
      format.html { redirect_to categoria_path, status: :see_other, notice: "Categorium was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_categoria
      @categoria = Categoria.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def categoria_params
      params.require(:categoria).permit(:nombre, :descripcion)
    end
end

app/controllers/categorias_controller.rb
class CategoriasController < ApplicationController
  before_action :set_categoria, only: %i[show edit update destroy]

  # GET /categorias or /categorias.json
  def index
    @categorias = Categoria.all
  end

  # GET /categorias/1 or /categorias/1.json
  def show
  end

  # GET /categorias/new
  def new
    @categoria = Categoria.new
  end

  # GET /categorias/1/edit
  def edit
  end

  # POST /categorias or /categorias.json
  def create
    @categoria = Categoria.new(categoria_params)

    respond_to do |format|
      if @categoria.save
        format.html { redirect_to @categoria, notice: "La categoría fue creada exitosamente." }
        format.json { render :show, status: :created, location: @categoria }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @categoria.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /categorias/1 or /categorias/1.json
  def update
    respond_to do |format|
      if @categoria.update(categoria_params)
        format.html { redirect_to @categoria, notice: "La categoría fue actualizada exitosamente." }
        format.json { render :show, status: :ok, location: @categoria }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @categoria.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categorias/1 or /categorias/1.json
  def destroy
    @categoria.destroy!

    respond_to do |format|
      format.html { redirect_to categorias_path, notice: "La categoría fue eliminada exitosamente.", status: :see_other }
      format.json { head :no_content }
    end
  end

  private

    # Use callbacks to share common setup or constraints between actions.
    def set_categoria
      @categoria = Categoria.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def categoria_params
      params.require(:categoria).permit(:nombre, :descripcion)
    end
end

app/controllers/tareas_controller.rb
class TareasController < ApplicationController
  before_action :set_tarea, only: %i[ show edit update destroy ]

  # GET /tareas or /tareas.json
  def index
    @tareas = Tarea.all
  end

  # GET /tareas/1 or /tareas/1.json
  def show
  end

  # GET /tareas/new
  def new
    @tarea = Tarea.new
  end

  # GET /tareas/1/edit
  def edit
  end

  # POST /tareas or /tareas.json
  def create
    @tarea = Tarea.new(tarea_params)

    respond_to do |format|
      if @tarea.save
        format.html { redirect_to @tarea, notice: "Tarea was successfully created." }
        format.json { render :show, status: :created, location: @tarea }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @tarea.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tareas/1 or /tareas/1.json
  def update
    respond_to do |format|
      if @tarea.update(tarea_params)
        format.html { redirect_to @tarea, notice: "Tarea was successfully updated." }
        format.json { render :show, status: :ok, location: @tarea }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @tarea.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tareas/1 or /tareas/1.json
  def destroy
    @tarea.destroy!

    respond_to do |format|
      format.html { redirect_to tareas_path, status: :see_other, notice: "Tarea was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_tarea
      @tarea = Tarea.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def tarea_params
      params.require(:tarea).permit(:nombre, :descripcion, :fecha_vencimiento, :categoria_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categoria_helper.rb
module CategoriaHelper
end

app/helpers/tareas_helper.rb
module TareasHelper
end

app/views/categoria/_form.html.haml
-# frozen_string_literal: true
= simple_form_for(@categoria, url: categorias_path) do |f|
  = f.error_notification
  = f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present?

  .form-inputs
    = f.input :nombre
    = f.input :descripcion

  .form-actions
    = f.button :submit

app/views/categoria/edit.html.haml
%h1 Editing categorium

= render 'form'

= link_to 'Show', @categorium
\|
= link_to 'Back', categoria_path

app/views/categoria/index.html.haml
%h1 Listado de categorías

%table
  %thead
    %tr
      %th Nombre
      %th Descripción
      %th
      %th
      %th

  %tbody
    - @categorias.each do |categoria|
      %tr
        %td= categoria.nombre
        %td= categoria.descripcion
        %td= link_to 'Mostrar', categoria_path(categoria)
        %td= link_to 'Editar', edit_categoria_path(categoria)
        %td= link_to 'Eliminar', categoria, method: :delete, data: { confirm: '¿Estás seguro?' }

%br

= link_to 'Nueva categoría', new_categoria_path

app/views/categoria/new.html.haml
%h1 New categorium

= render 'form'

= link_to 'Back', categoria_path

app/views/categoria/show.html.haml
%p#notice= notice

%p
  %b Nombre:
  = @categorium.nombre
%p
  %b Descripcion:
  = @categorium.descripcion

= link_to 'Edit', edit_categorium_path(@categorium)
\|
= link_to 'Back', categoria_path

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Organizador</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/tareas/_form.html.haml
-# frozen_string_literal: true
= simple_form_for(@tarea) do |f|
  = f.error_notification
  = f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present?

  .form-inputs
    = f.input :nombre
    = f.input :descripcion
    = f.input :fecha_vencimiento
    = f.association :categoria

  .form-actions
    = f.button :submit

app/views/tareas/edit.html.haml
%h1 Editing tarea

= render 'form'

= link_to 'Show', @tarea
\|
= link_to 'Back', tareas_path

app/views/tareas/index.html.haml
%h1 Listing tareas

%table
  %thead
    %tr
      %th Nombre
      %th Descripcion
      %th Fecha vencimiento
      %th Categoria
      %th
      %th
      %th

  %tbody
    - @tareas.each do |tarea|
      %tr
        %td= tarea.nombre
        %td= tarea.descripcion
        %td= tarea.fecha_vencimiento
        %td= tarea.categoria
        %td= link_to 'Show', tarea
        %td= link_to 'Edit', edit_tarea_path(tarea)
        %td= link_to 'Destroy', tarea, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Tarea', new_tarea_path

app/views/tareas/new.html.haml
%h1 New tarea

= render 'form'

= link_to 'Back', tareas_path

app/views/tareas/show.html.haml
%p#notice= notice

%p
  %b Nombre:
  = @tarea.nombre
%p
  %b Descripcion:
  = @tarea.descripcion
%p
  %b Fecha vencimiento:
  = @tarea.fecha_vencimiento
%p
  %b Categoria:
  = @tarea.categoria

= link_to 'Edit', edit_tarea_path(@tarea)
\|
= link_to 'Back', tareas_path